# Generated by Django 5.2.4 on 2025-08-15 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_watchlist_remove_propertyfeature_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlisted_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
